### PR TITLE
Database: LEAF-2193 - Upgrade DB for Custom Events

### PR DESCRIPTION
**Pull request by pete-nerantzinis**

### CODE REVIEW

**Review by raphaelfretter — APPROVED** [review]
Looks good to me

**Review by Pelentan — APPROVED** [review]
Looks good.

**Review by beingforthebenefit — APPROVED** [review]
Great

**Review by aerinkayne — APPROVED** [review]

**Review by gerald-todd — COMMENTED** [review]
Already reviewed on my personal account. This is my work-specific account now

**Pull request merged**
